// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbwecudqsqvnsukkabxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhid2VjdWRxc3F2bnN1a2thYnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1NjE2OTMsImV4cCI6MjEwMjEzNzY5M30.50kZQhB8PbVqTfkWVJMsz2JSF1CuoLmEQ7kE0YtFcM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});